const SITES = [
// ─── PREMIUM STREAMING ────────────────────────────────────────────────────
{id:1,  name:"Crunchyroll",       url:"https://www.crunchyroll.com",           cat:"premium",   lang:"EN", desc:"World's largest anime streaming service — simulcasts, dubs, manga."},
{id:2,  name:"Funimation",        url:"https://www.funimation.com",            cat:"premium",   lang:"EN", desc:"Premium dubbed & subbed anime, now merged with Crunchyroll."},
{id:3,  name:"HiDive",            url:"https://www.hidive.com",                cat:"premium",   lang:"EN", desc:"Premium anime with exclusives, simulcasts and classic catalogue."},
{id:4,  name:"Netflix Anime",     url:"https://www.netflix.com/browse/genre/7424", cat:"premium", lang:"EN", desc:"Netflix's growing anime category including Originals."},
{id:5,  name:"Hulu Anime",        url:"https://www.hulu.com/hub/anime",        cat:"premium",   lang:"EN", desc:"Hulu's anime hub with current and classic series."},
{id:6,  name:"Amazon Prime Anime",url:"https://www.amazon.com/s?i=instant-video&bbn=2858778011", cat:"premium", lang:"EN", desc:"Amazon Prime Video anime selection including exclusives."},
{id:7,  name:"Disney+ Anime",     url:"https://www.disneyplus.com",            cat:"premium",   lang:"EN", desc:"Disney+ carries Star Wars anime, National Geographic, and more."},
{id:8,  name:"Peacock Anime",     url:"https://www.peacocktv.com",             cat:"premium",   lang:"EN", desc:"NBCUniversal's streaming service with anime selection."},
{id:9,  name:"Tubi Anime",        url:"https://tubitv.com/categories/anime",   cat:"streaming", lang:"EN", desc:"Free ad-supported anime streaming — no subscription needed."},
{id:10, name:"Pluto TV Anime",    url:"https://pluto.tv/en/on-demand/categories/anime-en", cat:"streaming", lang:"EN", desc:"Free ad-supported live and on-demand anime channels."},
{id:11, name:"Plex Anime",        url:"https://www.plex.tv/en-us/watch-free/browse/#!?genre=Anime", cat:"streaming", lang:"EN", desc:"Free anime streaming via Plex's free tier."},
{id:12, name:"RetroCrush",        url:"https://www.retrocrush.tv",             cat:"streaming", lang:"EN", desc:"Classic and retro anime — free with ads, premium available."},
{id:13, name:"VRV",               url:"https://vrv.co",                        cat:"premium",   lang:"EN", desc:"Multi-channel streaming bundling Crunchyroll and others."},
{id:14, name:"Muse Asia",         url:"https://www.muse-asia.com",             cat:"streaming", lang:"EN", desc:"Legal free anime for Southeast Asia viewers."},
{id:15, name:"Bilibili Intl",     url:"https://www.bilibili.tv",               cat:"streaming", lang:"EN", desc:"Bilibili International — simulcasts and Asian drama."},
{id:16, name:"Wakanim",           url:"https://www.wakanim.tv",                cat:"premium",   lang:"FR", desc:"European anime streaming service (FR/DE/SE/NO and more)."},
{id:17, name:"ADN (AnimeDN)",     url:"https://animedigitalnetwork.fr",        cat:"premium",   lang:"FR", desc:"Anime Digital Network — French simulcasts and exclusives."},
{id:18, name:"AnimeLab",          url:"https://www.animelab.com",              cat:"premium",   lang:"EN", desc:"Australia/NZ anime streaming — now merged with Funimation."},
{id:19, name:"Stan Anime",        url:"https://www.stan.com.au/browse/genres/anime", cat:"premium", lang:"EN", desc:"Australian streaming with solid anime catalogue."},
{id:20, name:"AbemaTV",           url:"https://abema.tv",                      cat:"streaming", lang:"JP", desc:"Japanese free-to-air streaming with live simulcasts."},
{id:21, name:"iQIYI International",url:"https://www.iq.com",                  cat:"premium",   lang:"EN", desc:"Asian content hub — anime, Chinese drama, originals."},
{id:22, name:"WeTV (Tencent)",    url:"https://wetv.vip",                      cat:"streaming", lang:"EN", desc:"Tencent Video International — anime and Asian drama."},
{id:23, name:"Viu",               url:"https://www.viu.com",                   cat:"premium",   lang:"EN", desc:"Pan-Asian streaming covering anime and Korean drama."},
{id:24, name:"GKids",             url:"https://www.gkids.com",                 cat:"premium",   lang:"EN", desc:"Official home of Studio Ghibli films in North America."},
{id:25, name:"Shout! Factory TV", url:"https://www.shoutfactorytv.com",        cat:"streaming", lang:"EN", desc:"Free US streaming with classic anime dubbed titles."},

// ─── FREE / GREY AREA STREAMING ───────────────────────────────────────────
{id:30, name:"GogoAnime",         url:"https://gogoanime.gg",                  cat:"streaming", lang:"EN", desc:"One of the largest free anime streaming sites — huge catalogue."},
{id:31, name:"GogoAnime.dk",      url:"https://gogoanime.dk",                  cat:"streaming", lang:"EN", desc:"GogoAnime mirror — alternative domain."},
{id:32, name:"GogoAnime.be",      url:"https://gogoanimes.be",                 cat:"streaming", lang:"EN", desc:"GogoAnime mirror — .be domain."},
{id:33, name:"GogoAnime.nl",      url:"https://gogoanime.nl",                  cat:"streaming", lang:"EN", desc:"GogoAnime mirror — .nl domain."},
{id:34, name:"GogoAnime.id",      url:"https://gogoanime.id",                  cat:"streaming", lang:"EN", desc:"GogoAnime Indonesian mirror."},
{id:35, name:"9anime",            url:"https://9anime.to",                     cat:"streaming", lang:"EN", desc:"Popular multi-server anime streaming site."},
{id:36, name:"9anime.pl",         url:"https://9anime.pl",                     cat:"streaming", lang:"EN", desc:"9anime mirror — .pl domain."},
{id:37, name:"9anime.gs",         url:"https://9anime.gs",                     cat:"streaming", lang:"EN", desc:"9anime mirror — .gs domain."},
{id:38, name:"Aniwatch",          url:"https://aniwatch.to",                   cat:"streaming", lang:"EN", desc:"Clean interface, fast servers — formerly Zoro.to."},
{id:39, name:"HiAnime",           url:"https://hianime.to",                    cat:"streaming", lang:"EN", desc:"HiAnime — multi-server streaming, same team as Aniwatch."},
{id:40, name:"Zoro.to",           url:"https://zoro.to",                       cat:"streaming", lang:"EN", desc:"Original Zoro domain — high quality streams with subtitles."},
{id:41, name:"AnimePahe",         url:"https://animepahe.ru",                  cat:"streaming", lang:"EN", desc:"Low bandwidth, high quality — great for slower connections."},
{id:42, name:"AnimePahe.org",     url:"https://animepahe.org",                 cat:"streaming", lang:"EN", desc:"AnimePahe alternate domain."},
{id:43, name:"AnimeSuge",         url:"https://animesuge.io",                  cat:"streaming", lang:"EN", desc:"Anime streaming with multiple servers and HD quality."},
{id:44, name:"AnimeDAO",          url:"https://animedao.to",                   cat:"streaming", lang:"EN", desc:"Clean site, frequently updated with new episodes."},
{id:45, name:"AnimeOwl",          url:"https://animeowl.me",                   cat:"streaming", lang:"EN", desc:"Minimal ads, decent library with good subtitle options."},
{id:46, name:"Aniwave",           url:"https://aniwave.to",                    cat:"streaming", lang:"EN", desc:"Large catalogue streaming site with multi-server support."},
{id:47, name:"Kaido",             url:"https://kaido.to",                      cat:"streaming", lang:"EN", desc:"Kaido anime streaming — clean UI, fast CDN."},
{id:48, name:"AnixAnime",         url:"https://anix.to",                       cat:"streaming", lang:"EN", desc:"Anix — solid streaming site with regular updates."},
{id:49, name:"AniCrush",          url:"https://anicrush.to",                   cat:"streaming", lang:"EN", desc:"AniCrush streaming — multiple resolution options."},
{id:50, name:"AnimeVibe",         url:"https://animevibe.tv",                  cat:"streaming", lang:"EN", desc:"Community-driven streaming with voting and reviews."},
{id:51, name:"AnimeKisa",         url:"https://animekisa.tv",                  cat:"streaming", lang:"EN", desc:"Clean fast streaming with dub/sub toggle."},
{id:52, name:"AnimeFrenzy",       url:"https://animefrenzy.net",               cat:"streaming", lang:"EN", desc:"AnimeFrenzy — HD streaming with large catalogue."},
{id:53, name:"AnimeLand",         url:"https://animeland.tv",                  cat:"streaming", lang:"EN", desc:"AnimeLand streaming portal with schedule tracker."},
{id:54, name:"AnimeHub",          url:"https://animehub.ac",                   cat:"streaming", lang:"EN", desc:"AnimeHub .ac — clean streaming with recommended lists."},
{id:55, name:"AnimeRush",         url:"https://animerush.tv",                  cat:"streaming", lang:"EN", desc:"Anime Rush — daily updates, dubbed and subbed."},
{id:56, name:"AnimeUltima",       url:"https://animeultima.eu",                cat:"streaming", lang:"EN", desc:"AnimeUltima — long-running streaming site with community."},
{id:57, name:"AnimeHero",         url:"https://animehero.io",                  cat:"streaming", lang:"EN", desc:"AnimeHero — fast CDN, no-registration streaming."},
{id:58, name:"AnimeGlare",        url:"https://animeglare.com",                cat:"streaming", lang:"EN", desc:"AnimeGlare — solid catalogue, multiple mirror servers."},
{id:59, name:"AnimeStreams",      url:"https://animestreams.tv",               cat:"streaming", lang:"EN", desc:"AnimeStreams — variety of genres, HD quality."},
{id:60, name:"AnimeHeaven",       url:"https://animeheaven.eu",                cat:"streaming", lang:"EN", desc:"AnimeHeaven — long-running site with classic and current."},
{id:61, name:"AniMixPlay",        url:"https://animixplay.to",                 cat:"streaming", lang:"EN", desc:"AniMixPlay — popular site with community features."},
{id:62, name:"YugenAnime",        url:"https://yugenanime.tv",                 cat:"streaming", lang:"EN", desc:"YugenAnime — sleek UI, good subtitle quality."},
{id:63, name:"AllAnime",          url:"https://allanime.to",                   cat:"streaming", lang:"EN", desc:"AllAnime — wide catalogue including airing and older shows."},
{id:64, name:"AnimeKaizoku",      url:"https://animekaizoku.com",              cat:"streaming", lang:"EN", desc:"AnimeKaizoku — mini-encoded downloads and streaming."},
{id:65, name:"WatchAnime",        url:"https://watchanime.video",              cat:"streaming", lang:"EN", desc:"WatchAnime.video — straightforward catalogue browser."},
{id:66, name:"AnimeKai",          url:"https://animekai.to",                   cat:"streaming", lang:"EN", desc:"AnimeKai — recent site with clean design and fast servers."},
{id:67, name:"AnimeFreak",        url:"https://animefreak.tv",                 cat:"streaming", lang:"EN", desc:"AnimeFreak — established site, large library."},
{id:68, name:"OtakuStream",       url:"https://otakustream.cc",                cat:"streaming", lang:"EN", desc:"OtakuStream — anime community with streaming hub."},
{id:69, name:"AnimeTV",           url:"https://anime-tv.com",                  cat:"streaming", lang:"EN", desc:"AnimeTV — clean site, works on mobile."},
{id:70, name:"MasterAnime",       url:"https://masterani.me",                  cat:"streaming", lang:"EN", desc:"MasterAnime — older site with curated catalogue."},
{id:71, name:"AnimeXin",          url:"https://animexin.vip",                  cat:"streaming", lang:"EN", desc:"AnimeXin VIP — multi-server with HD options."},
{id:72, name:"AnimeFlux",         url:"https://animeflux.net",                 cat:"streaming", lang:"EN", desc:"AnimeFlux — newer site with fast load times."},
{id:73, name:"AnimeCloud",        url:"https://animecloud.cc",                 cat:"streaming", lang:"EN", desc:"AnimeCloud — cloud-based CDN delivery for smooth streaming."},
{id:74, name:"AniKing",           url:"https://aniking.me",                    cat:"streaming", lang:"EN", desc:"AniKing — HD streaming, recent simulcasts included."},
{id:75, name:"AnimeID",           url:"https://animeid.tv",                    cat:"streaming", lang:"EN", desc:"AnimeID — Indonesian-accessible streaming site."},
{id:76, name:"AnimeOWL",          url:"https://animeowl.live",                 cat:"streaming", lang:"EN", desc:"AnimeOwl alternate domain."},
{id:77, name:"AnimeKhor",         url:"https://animekhor.xyz",                 cat:"streaming", lang:"EN", desc:"AnimeKhor — fast mirrors, new episodes quickly."},
{id:78, name:"AnimeNexus",        url:"https://animenexus.me",                 cat:"streaming", lang:"EN", desc:"AnimeNexus — clean portal with multiple quality options."},
{id:79, name:"AnimeXD",           url:"https://animexd.me",                    cat:"streaming", lang:"EN", desc:"AnimeXD — large catalogue, minimal pop-ups."},
{id:80, name:"AnimeDD",           url:"https://animedd.org",                   cat:"streaming", lang:"EN", desc:"AnimeDD — direct download and stream hybrid."},
{id:81, name:"AnimeStation",      url:"https://animestation.me",               cat:"streaming", lang:"EN", desc:"AnimeStation — scheduled releases, tracker built-in."},
{id:82, name:"AnimeWorld (EN)",   url:"https://animeworld.biz",                cat:"streaming", lang:"EN", desc:"English AnimeWorld portal with wide genre coverage."},
{id:83, name:"KissAnime",         url:"https://kissanime.ac",                  cat:"streaming", lang:"EN", desc:"KissAnime mirror — one of the original free streaming sites."},
{id:84, name:"KissAnime.nz",      url:"https://kissanime.nz",                  cat:"streaming", lang:"EN", desc:"KissAnime .nz mirror domain."},
{id:85, name:"KissAnime.sh",      url:"https://kissanime.sh",                  cat:"streaming", lang:"EN", desc:"KissAnime .sh mirror domain."},
{id:86, name:"KissAnime.info",    url:"https://kissanime.info",                cat:"streaming", lang:"EN", desc:"KissAnime .info mirror domain."},
{id:87, name:"AnimeUltra",        url:"https://animeultra.net",                cat:"streaming", lang:"EN", desc:"AnimeUltra — fast streaming with auto-next-episode."},
{id:88, name:"AnimePlus",         url:"https://animeplus.tv",                  cat:"streaming", lang:"EN", desc:"AnimePlus — good for older/classic series."},
{id:89, name:"OtakuTv",           url:"https://otakutv.tv",                    cat:"streaming", lang:"EN", desc:"OtakuTv — community focused streaming portal."},
{id:90, name:"AnimeFactory",      url:"https://animefactory.net",              cat:"streaming", lang:"EN", desc:"AnimeFactory — solid all-round streaming catalogue."},
{id:91, name:"Anime4You",         url:"https://www.anime4you.one",             cat:"streaming", lang:"DE", desc:"German anime streaming site — large German-dubbed library."},
{id:92, name:"AniCloud",          url:"https://anicloud.io",                   cat:"streaming", lang:"DE", desc:"German-language anime streaming, dub and sub options."},
{id:93, name:"AniTube",           url:"https://anitube.online",                cat:"streaming", lang:"DE", desc:"German anime tube-style streaming platform."},
{id:94, name:"SerienStream",      url:"https://serienstream.to",               cat:"streaming", lang:"DE", desc:"German multi-genre streaming including anime."},
{id:95, name:"AnimeZone (DE)",    url:"https://www.animezone.eu",              cat:"streaming", lang:"DE", desc:"German-language anime zone — subbed and dubbed content."},
{id:96, name:"AnimeBase (DE)",    url:"https://animebase.me",                  cat:"streaming", lang:"DE", desc:"German anime base — community and streaming combined."},
{id:97, name:"AnimeFlv (ES)",     url:"https://www.animeflv.net",              cat:"streaming", lang:"ES", desc:"Largest Spanish-language anime streaming site."},
{id:98, name:"AnimeFlv.io",       url:"https://animeflv.io",                   cat:"streaming", lang:"ES", desc:"AnimeFlv alternate domain — Spanish subtitles."},
{id:99, name:"JKAnime",           url:"https://jkanime.net",                   cat:"streaming", lang:"ES", desc:"Spanish anime streaming — JKAnime, popular in LATAM."},
{id:100,name:"MonosChinos",       url:"https://monoschinos.com",               cat:"streaming", lang:"ES", desc:"Spanish-language streaming — popular in Latin America."},
{id:101,name:"TioAnime",          url:"https://tioanime.com",                  cat:"streaming", lang:"ES", desc:"TioAnime — Spanish streaming with HD quality."},
{id:102,name:"AnimeFenix",        url:"https://animefenix.tv",                 cat:"streaming", lang:"ES", desc:"AnimeFenix — Spanish streaming, frequent updates."},
{id:103,name:"AnimeChile",        url:"https://www.animechile.cl",             cat:"streaming", lang:"ES", desc:"Chilean anime community and streaming portal."},
{id:104,name:"InAnime",           url:"https://inanime.net",                   cat:"streaming", lang:"ES", desc:"InAnime — Spanish streaming with comment sections."},
{id:105,name:"OtakuVerse",        url:"https://otakuverse.net",                cat:"streaming", lang:"ES", desc:"Spanish otaku community and streaming site."},
{id:106,name:"AnimeSama (FR)",    url:"https://anime-sama.fr",                 cat:"streaming", lang:"FR", desc:"Largest French-language free anime streaming site."},
{id:107,name:"VostFree",          url:"https://vostfree.tv",                   cat:"streaming", lang:"FR", desc:"VOSTFR anime streaming — French subtitles focus."},
{id:108,name:"Neko-Sama (FR)",    url:"https://www.neko-sama.fr",              cat:"streaming", lang:"FR", desc:"Neko-Sama — French streaming, clean UI."},
{id:109,name:"OtakuFR",           url:"https://otakufr.tv",                    cat:"streaming", lang:"FR", desc:"OtakuFR — French community and streaming."},
{id:110,name:"Nautiljon",         url:"https://www.nautiljon.com",             cat:"streaming", lang:"FR", desc:"French anime database and streaming aggregator."},
{id:111,name:"AnimeFire (PT)",    url:"https://animefire.net",                 cat:"streaming", lang:"PT", desc:"Brazilian anime streaming — AnimeFire, large PTBR library."},
{id:112,name:"BetterAnime (PT)",  url:"https://betteranime.net",               cat:"streaming", lang:"PT", desc:"Brazilian streaming — BetterAnime, HD quality."},
{id:113,name:"AnimesOnline.cc",   url:"https://animesonline.cc",               cat:"streaming", lang:"PT", desc:"Portuguese-language streaming with broad catalogue."},
{id:114,name:"AnimeZone (PL)",    url:"https://animezone.pl",                  cat:"streaming", lang:"EN", desc:"Polish anime zone — Polish subs and streaming."},
{id:115,name:"AnimeWorld (IT)",   url:"https://www.animeworld.so",             cat:"streaming", lang:"IT", desc:"Largest Italian anime streaming site."},
{id:116,name:"AnimeSaturn (IT)",  url:"https://www.animesaturn.tv",            cat:"streaming", lang:"IT", desc:"AnimeSaturn — Italian streaming, HD quality."},
{id:117,name:"AnimeGo (RU)",      url:"https://animego.org",                   cat:"streaming", lang:"RU", desc:"Russian-language anime streaming — AnimeGo."},
{id:118,name:"AniLibria (RU)",    url:"https://www.anilibria.tv",              cat:"streaming", lang:"RU", desc:"Russian fansub group with streaming — AniLibria."},
{id:119,name:"JutsuAnime (RU)",   url:"https://jutsu.team",                    cat:"streaming", lang:"RU", desc:"Russian anime streaming — Jutsu, high quality."},
{id:120,name:"AnimoTV",           url:"https://www.animotv.com",               cat:"streaming", lang:"EN", desc:"AnimoTV — streaming with community voting features."},

// ─── DUBBED FOCUSED ───────────────────────────────────────────────────────
{id:130,name:"DubHappy",          url:"https://www.dubhappy.com",              cat:"dubbed",    lang:"EN", desc:"Dubbed-first streaming — large English dub library."},
{id:131,name:"AnimeDubbed.net",   url:"https://animedubbed.net",               cat:"dubbed",    lang:"EN", desc:"Dedicated dubbed anime streaming portal."},
{id:132,name:"WatchDubAnime",     url:"https://watchdubanime.com",             cat:"dubbed",    lang:"EN", desc:"Dub-only focused streaming site."},
{id:133,name:"AnimeDub.TV",       url:"https://animedub.tv",                   cat:"dubbed",    lang:"EN", desc:"AnimeDub — all dubbed, all the time."},
{id:134,name:"KissCartoon",       url:"https://kisscartoon.sh",                cat:"dubbed",    lang:"EN", desc:"KissCartoon — dubbed anime and western cartoons."},
{id:135,name:"WatchCartoonOnline",url:"https://www.watchcartoononline.com",    cat:"dubbed",    lang:"EN", desc:"Cartoons + dubbed anime streaming, no account required."},
{id:136,name:"Dub.Watch",         url:"https://dub.watch",                     cat:"dubbed",    lang:"EN", desc:"Dub.Watch — curated English dubbed anime library."},

// ─── MANGA ─────────────────────────────────────────────────────────────────
{id:140,name:"MangaDex",          url:"https://mangadex.org",                  cat:"manga",     lang:"EN", desc:"Community-run scanlation hub — 60+ languages, huge catalogue."},
{id:141,name:"MangaPlus",         url:"https://mangaplus.shueisha.co.jp",      cat:"manga",     lang:"EN", desc:"Official Shueisha simulpub — Naruto, One Piece, Bleach and more."},
{id:142,name:"Viz Media",         url:"https://www.viz.com/read",              cat:"manga",     lang:"EN", desc:"Official Viz/Shonen Jump manga — free 3-chapter preview."},
{id:143,name:"Shonen Jump (US)",  url:"https://shonenjump.viz.com",            cat:"manga",     lang:"EN", desc:"Viz Shonen Jump portal — digital chapters and news."},
{id:144,name:"ComicK",            url:"https://comick.io",                     cat:"manga",     lang:"EN", desc:"ComicK — fast, clean manga reader with multi-language support."},
{id:145,name:"Bato.to",           url:"https://bato.to",                       cat:"manga",     lang:"EN", desc:"Bato.to — community scanlation aggregator, many languages."},
{id:146,name:"MangaSee",          url:"https://mangasee123.com",               cat:"manga",     lang:"EN", desc:"MangaSee — official scans from publishers, good quality."},
{id:147,name:"MangaKakalot",      url:"https://mangakakalot.com",              cat:"manga",     lang:"EN", desc:"MangaKakalot — large library, fast loading pages."},
{id:148,name:"MangaNelo",         url:"https://manganelo.com",                 cat:"manga",     lang:"EN", desc:"MangaNelo — sister site to Kakalot, same large library."},
{id:149,name:"MangaHere",         url:"https://www.mangahere.cc",              cat:"manga",     lang:"EN", desc:"MangaHere — established reader, mobile-friendly."},
{id:150,name:"MangaFox",          url:"https://fanfox.net",                    cat:"manga",     lang:"EN", desc:"FanFox/MangaFox — classic reader, deep catalogue."},
{id:151,name:"MangaOwl",          url:"https://mangaowl.io",                   cat:"manga",     lang:"EN", desc:"MangaOwl — clean reader with bookmark sync."},
{id:152,name:"MangaReader",       url:"https://mangareader.to",                cat:"manga",     lang:"EN", desc:"MangaReader.to — side-by-side or vertical reading modes."},
{id:153,name:"MangaBuddy",        url:"https://mangabuddy.com",                cat:"manga",     lang:"EN", desc:"MangaBuddy — frequent updates, wide genre selection."},
{id:154,name:"MangaTx",           url:"https://mangatx.com",                   cat:"manga",     lang:"EN", desc:"MangaTx — dark mode reader, good mobile support."},
{id:155,name:"Mangago",           url:"https://www.mangago.me",                cat:"manga",     lang:"EN", desc:"Mangago — strong shoujo and BL/GL focus."},
{id:156,name:"MangaFreak",        url:"https://mangafreak.net",                cat:"manga",     lang:"EN", desc:"MangaFreak — no-account reading, lots of genres."},
{id:157,name:"MangaHasu",         url:"https://mangahasu.se",                  cat:"manga",     lang:"EN", desc:"MangaHasu — Swedish domain, global manga catalogue."},
{id:158,name:"MangaJar",          url:"https://mangajar.com",                  cat:"manga",     lang:"EN", desc:"MangaJar — clean reading experience, dark mode."},
{id:159,name:"ReadManga",         url:"https://readmanga.online",              cat:"manga",     lang:"EN", desc:"ReadManga — straightforward reader, large library."},
{id:160,name:"MangaTown",         url:"https://www.mangatown.com",             cat:"manga",     lang:"EN", desc:"MangaTown — older established site with classic series."},
{id:161,name:"KissManga",         url:"https://kissmanga.org",                 cat:"manga",     lang:"EN", desc:"KissManga — mirror of the famous original kissmanga."},
{id:162,name:"MangaStream (arc)", url:"https://mangastream.net",               cat:"manga",     lang:"EN", desc:"MangaStream archive — classic scanlations preserved."},
{id:163,name:"FlameComics",       url:"https://flamecomics.xyz",               cat:"manga",     lang:"EN", desc:"Flame Comics — scanlation group reader."},
{id:164,name:"AsuraScans",        url:"https://asurascans.com",                cat:"manga",     lang:"EN", desc:"Asura Scans — top manhwa and manga translation group."},
{id:165,name:"ReaperScans",       url:"https://reaperscans.com",               cat:"manga",     lang:"EN", desc:"Reaper Scans — popular manhwa translation group."},
{id:166,name:"LuminousScans",     url:"https://luminousscans.com",             cat:"manga",     lang:"EN", desc:"Luminous Scans — quality manhwa translations."},
{id:167,name:"ColoredManga",      url:"https://coloredmanga.com",              cat:"manga",     lang:"EN", desc:"ColoredManga — digitally coloured manga chapters."},
{id:168,name:"MangaZone",         url:"https://mangazone.org",                 cat:"manga",     lang:"EN", desc:"MangaZone — classic reader with wide genre tags."},
{id:169,name:"MangaLife",         url:"https://manga.life",                    cat:"manga",     lang:"EN", desc:"MangaLife — sister site to MangaSee, official scans."},
{id:170,name:"NightScans",        url:"https://night-scans.com",               cat:"manga",     lang:"EN", desc:"Night Scans — active scanlation group."},
{id:171,name:"MangaMonks",        url:"https://mangamonks.com",                cat:"manga",     lang:"EN", desc:"MangaMonks — updated catalogue, clean UI."},
{id:172,name:"MangaKissa",        url:"https://mangakissa.com",                cat:"manga",     lang:"EN", desc:"MangaKissa — café-themed manga reader."},
{id:173,name:"MangaIn",           url:"https://mangain.me",                    cat:"manga",     lang:"EN", desc:"MangaIn — modern reader with chapter progress."},
{id:174,name:"MangaGG",           url:"https://mangagg.com",                   cat:"manga",     lang:"EN", desc:"MangaGG — simple fast reader, mobile friendly."},
{id:175,name:"CatManga",          url:"https://catmanga.org",                  cat:"manga",     lang:"EN", desc:"CatManga — quality typeset scanlations."},

// ─── MANHWA / MANHUA ───────────────────────────────────────────────────────
{id:180,name:"Webtoon (Official)",url:"https://www.webtoons.com",              cat:"manhwa",    lang:"EN", desc:"Official LINE Webtoon platform — hundreds of free manhwa."},
{id:181,name:"Tapas",             url:"https://tapas.io",                      cat:"manhwa",    lang:"EN", desc:"Tapas — manhwa, webcomics, and light novels."},
{id:182,name:"Lezhin Comics",     url:"https://www.lezhin.com",                cat:"manhwa",    lang:"EN", desc:"Premium manhwa platform — mature and romance titles."},
{id:183,name:"ManhwaTop",         url:"https://manhwatop.com",                 cat:"manhwa",    lang:"EN", desc:"ManhwaTop — aggregator for Korean manhwa."},
{id:184,name:"ManhwaRaw",         url:"https://manhwaraw.com",                 cat:"manhwa",    lang:"EN", desc:"ManhwaRaw — raw Korean manhwa chapters."},
{id:185,name:"Toomics",           url:"https://toomics.com",                   cat:"manhwa",    lang:"EN", desc:"Toomics — premium full-colour Korean manhwa."},
{id:186,name:"PocketComics",      url:"https://www.pocketcomics.com",          cat:"manhwa",    lang:"EN", desc:"Pocket Comics — mobile-first manhwa platform."},
{id:187,name:"MangaDex (manhwa)", url:"https://mangadex.org/?types=manhwa",    cat:"manhwa",    lang:"EN", desc:"MangaDex filtered to manhwa — huge scanlation library."},
{id:188,name:"Manhuaus",          url:"https://manhuaus.com",                  cat:"manhwa",    lang:"EN", desc:"Manhuaus — Chinese manhua reader, translated to English."},
{id:189,name:"ManhuaScan",        url:"https://manhuascan.com",                cat:"manhwa",    lang:"EN", desc:"ManhuaScan — Chinese manhua with fast English translation."},
{id:190,name:"ManhuaPlus",        url:"https://manhuaplus.com",                cat:"manhwa",    lang:"EN", desc:"ManhuaPlus — manhua aggregator, colour pages."},

// ─── DOWNLOADS / TORRENTS ──────────────────────────────────────────────────
{id:200,name:"Nyaa.si",           url:"https://nyaa.si",                       cat:"downloads", lang:"EN", desc:"#1 anime torrent site — every release, every group."},
{id:201,name:"Nyaa.land",         url:"https://nyaa.land",                     cat:"downloads", lang:"EN", desc:"Nyaa mirror — full catalogue backup."},
{id:202,name:"TokyoTosho",        url:"https://www.tokyotosho.info",           cat:"downloads", lang:"EN", desc:"TokyoTosho — torrent and DDL index for anime/manga."},
{id:203,name:"AnimeTosho",        url:"https://animetosho.org",                cat:"downloads", lang:"EN", desc:"AnimeTosho — Nyaa mirror with DDL links from multiple hosts."},
{id:204,name:"SubsPlease",        url:"https://subsplease.org",                cat:"downloads", lang:"EN", desc:"SubsPlease — weekly simulcast rips, 1080p WEB."},
{id:205,name:"Erai-Raws",         url:"https://www.erai-raws.info",            cat:"downloads", lang:"EN", desc:"Erai-Raws — raw + multi-sub simulcast releases."},
{id:206,name:"HorribleSubs",      url:"https://horriblesubs.info",             cat:"downloads", lang:"EN", desc:"HorribleSubs archive — Crunchyroll rips (defunct but archived)."},
{id:207,name:"AnimeBytes",        url:"https://animebytes.tv",                 cat:"downloads", lang:"EN", desc:"AnimeBytes — invite-only private tracker, best quality."},
{id:208,name:"BakaBT",            url:"https://bakabt.me",                     cat:"downloads", lang:"EN", desc:"BakaBT — private tracker, completed series focus."},
{id:209,name:"Judas",             url:"https://judasanlime.net",               cat:"downloads", lang:"EN", desc:"Judas — mini-encoded releases for limited bandwidth."},

// ─── INFO / DATABASE ────────────────────────────────────────────────────────
{id:220,name:"MyAnimeList",       url:"https://myanimelist.net",               cat:"info",      lang:"EN", desc:"The world's largest anime/manga database and tracker."},
{id:221,name:"AniList",           url:"https://anilist.co",                    cat:"info",      lang:"EN", desc:"Modern anime tracker — social features, GraphQL API."},
{id:222,name:"AniDB",             url:"https://anidb.net",                     cat:"info",      lang:"EN", desc:"AniDB — most detailed per-episode anime database."},
{id:223,name:"Kitsu",             url:"https://kitsu.io",                      cat:"info",      lang:"EN", desc:"Kitsu — social anime tracker with beautiful UI."},
{id:224,name:"Anime-Planet",      url:"https://www.anime-planet.com",          cat:"info",      lang:"EN", desc:"Anime-Planet — recommendation engine + tracker."},
{id:225,name:"AniSearch",         url:"https://www.anisearch.com",             cat:"info",      lang:"DE", desc:"AniSearch — German/English anime database with reviews."},
{id:226,name:"LiveChart",         url:"https://www.livechart.me",              cat:"info",      lang:"EN", desc:"LiveChart — seasonal charts with countdown timers."},
{id:227,name:"AniTrendz",         url:"https://anitrendz.com",                 cat:"info",      lang:"EN", desc:"AniTrendz — trending anime polls and charts."},
{id:228,name:"Notify.moe",        url:"https://notify.moe",                    cat:"info",      lang:"EN", desc:"Notify.moe — open-source anime tracker with API."},
{id:229,name:"AniChart",          url:"https://anichart.net",                  cat:"info",      lang:"EN", desc:"AniChart — beautiful seasonal anime chart viewer."},
{id:230,name:"Simkl",             url:"https://simkl.com",                     cat:"info",      lang:"EN", desc:"Simkl — multi-purpose tracker for anime, TV and movies."},
{id:231,name:"Anitrakt",          url:"https://anitrakt.tv",                   cat:"info",      lang:"EN", desc:"AniTrakt — links AniList/MAL to Trakt.tv for cross-tracking."},
{id:232,name:"Anime Fillerlist",  url:"https://www.animefillerlist.com",       cat:"info",      lang:"EN", desc:"Filler list guide — skip fillers in long-running series."},
{id:233,name:"AnimeCharacter DB", url:"https://www.animecharactersdatabase.com",cat:"info",     lang:"EN", desc:"Anime Characters Database — search by character traits."},
{id:234,name:"AniSearch (DE)",    url:"https://www.anisearch.de",              cat:"info",      lang:"DE", desc:"AniSearch German portal — reviews and news in German."},
{id:235,name:"AniDB (lite)",      url:"https://anidb.net/latest/anime/",       cat:"info",      lang:"EN", desc:"AniDB latest anime additions feed."},
{id:236,name:"SakugaBooru",       url:"https://www.sakugabooru.com",           cat:"info",      lang:"EN", desc:"Sakugabooru — animation sakuga clips database."},
{id:237,name:"Anime Sols",        url:"https://www.animesols.com",             cat:"info",      lang:"EN", desc:"AnimeSols — classic anime licensing crowdfunding."},
{id:238,name:"Behind the Voice",  url:"https://www.behindthevoiceactors.com",  cat:"info",      lang:"EN", desc:"Behind the Voice Actors — VA credits for anime and dubs."},
{id:239,name:"Anime Index",       url:"https://animeindex.org",                cat:"info",      lang:"EN", desc:"Anime Index — comprehensive directory and rating site."},

// ─── NEWS ─────────────────────────────────────────────────────────────────
{id:250,name:"Anime News Network",url:"https://www.animenewsnetwork.com",      cat:"news",      lang:"EN", desc:"ANN — the authoritative English-language anime news source."},
{id:251,name:"Crunchyroll News",  url:"https://www.crunchyroll.com/news",      cat:"news",      lang:"EN", desc:"Crunchyroll editorial — previews, reviews and features."},
{id:252,name:"Otaku USA",         url:"https://otakuusamagazine.com",          cat:"news",      lang:"EN", desc:"Otaku USA Magazine — anime, manga and Japanese culture."},
{id:253,name:"Anime! Anime!",     url:"https://animeanime.jp",                 cat:"news",      lang:"JP", desc:"Japanese anime news — official announcements and coverage."},
{id:254,name:"Natalie Anime",     url:"https://natalie.mu/comic",              cat:"news",      lang:"JP", desc:"Natalie — popular Japanese pop culture news."},
{id:255,name:"AnimeCorner",       url:"https://animecorner.me",                cat:"news",      lang:"EN", desc:"AnimeCorner — seasonal rankings, polls and features."},
{id:256,name:"Anime Trending",    url:"https://www.anitrendz.net",             cat:"news",      lang:"EN", desc:"AniTrendz — weekly trending anime charts and rankings."},
{id:257,name:"Anime Senpai",      url:"https://www.animesenpai.net",           cat:"news",      lang:"EN", desc:"AnimeSenpai — news, reviews and season previews."},
{id:258,name:"AnimeHype",         url:"https://animehype.net",                 cat:"news",      lang:"EN", desc:"AnimeHype — hype tracking and release news."},
{id:259,name:"Dengeki Online",    url:"https://dengekionline.com",             cat:"news",      lang:"JP", desc:"Dengeki Online — game and anime news from ASCII Media Works."},
{id:260,name:"MoAR",             url:"https://www.moar.online",               cat:"news",      lang:"EN", desc:"MoAR — monthly anime review digest."},

// ─── SCHEDULE ─────────────────────────────────────────────────────────────
{id:270,name:"AnimeSchedule.net", url:"https://animeschedule.net",             cat:"schedule",  lang:"EN", desc:"Best airing schedule — timezone-aware, stream links."},
{id:271,name:"AniChart Seasonal", url:"https://anichart.net",                  cat:"schedule",  lang:"EN", desc:"AniChart — season overview with trailers and scores."},
{id:272,name:"LiveChart Seasonal",url:"https://www.livechart.me/season",       cat:"schedule",  lang:"EN", desc:"LiveChart seasonal view with countdown timers."},
{id:273,name:"MAL Airing",        url:"https://myanimelist.net/topanime.php?type=airing", cat:"schedule", lang:"EN", desc:"MAL's currently airing top-rated list."},
{id:274,name:"AniList Airing",    url:"https://anilist.co/search/anime/this-season", cat:"schedule", lang:"EN", desc:"AniList seasonal browser with tracking integration."},

// ─── COMMUNITY ─────────────────────────────────────────────────────────────
{id:280,name:"Reddit r/anime",    url:"https://www.reddit.com/r/anime",        cat:"community", lang:"EN", desc:"Largest English-language anime subreddit — 4M+ members."},
{id:281,name:"Reddit r/manga",    url:"https://www.reddit.com/r/manga",        cat:"community", lang:"EN", desc:"Reddit manga community — scanlation news and discussion."},
{id:282,name:"Reddit r/animesuggest",url:"https://www.reddit.com/r/Animesuggest",cat:"community",lang:"EN",desc:"Anime recommendations subreddit."},
{id:283,name:"MyAnimeList Forums",url:"https://myanimelist.net/forum/",        cat:"community", lang:"EN", desc:"MAL Forums — episode discussion threads and club boards."},
{id:284,name:"AniList Forums",    url:"https://anilist.co/forum",              cat:"community", lang:"EN", desc:"AniList activity feed and community forums."},
{id:285,name:"4chan /a/",         url:"https://boards.4channel.org/a/",        cat:"community", lang:"EN", desc:"4chan Anime & Manga board — fast episode discussion threads."},
{id:286,name:"AnimeForum.com",    url:"https://www.animeforum.com",            cat:"community", lang:"EN", desc:"AnimeForum — long-running community forum."},
{id:287,name:"ANN Forums",        url:"https://www.animenewsnetwork.com/bbs/", cat:"community", lang:"EN", desc:"Anime News Network community boards."},
{id:288,name:"Anime UK News",     url:"https://animeuknews.net",               cat:"community", lang:"EN", desc:"UK-focused anime community and news."},

// ─── LEARNING / JAPANESE ──────────────────────────────────────────────────
{id:300,name:"Animelon",          url:"https://animelon.com",                  cat:"learning",  lang:"EN", desc:"Watch anime with interactive Japanese subtitles — learn while watching."},
{id:301,name:"ImmersionKit",      url:"https://www.immersionkit.com",          cat:"learning",  lang:"EN", desc:"Search and listen to anime sentences — immersion learning tool."},
{id:302,name:"TheMoeWay",         url:"https://learnjapanese.moe",             cat:"learning",  lang:"EN", desc:"The Moe Way — immersion-based Japanese learning guide."},
{id:303,name:"WaniKani",          url:"https://www.wanikani.com",              cat:"learning",  lang:"EN", desc:"WaniKani — kanji and vocab via spaced repetition."},
{id:304,name:"JapanesePod101",    url:"https://www.japanesepod101.com",        cat:"learning",  lang:"EN", desc:"JapanesePod101 — audio and video Japanese lessons."},
{id:305,name:"NHK World Japanese",url:"https://www3.nhk.or.jp/nhkworld/en/learn/", cat:"learning", lang:"EN", desc:"NHK official free Japanese learning resources."},
{id:306,name:"Anime Transcript",  url:"https://github.com/andyfang1989/Anime-Transcript", cat:"learning", lang:"EN", desc:"Anime transcript database for Japanese learning."},
{id:307,name:"Subs2SRS",          url:"https://subs2srs.sourceforge.net",      cat:"learning",  lang:"EN", desc:"Subs2SRS — create Anki cards from anime subtitles."},

// ─── MUSIC / OST ──────────────────────────────────────────────────────────
{id:320,name:"AnimeOST.net",      url:"https://animeost.net",                  cat:"music",     lang:"EN", desc:"Anime OST downloads and streaming — huge database."},
{id:321,name:"Chosic Anime",      url:"https://www.chosic.com/anime-music/",   cat:"music",     lang:"EN", desc:"Chosic anime music discovery and playlist tools."},
{id:322,name:"AnimeMusicVideos",  url:"https://www.animemusicvideos.org",      cat:"music",     lang:"EN", desc:"AMV.org — largest archive of fan-made anime music videos."},
{id:323,name:"Anime Songs Lyrics",url:"https://www.animelyrics.com",           cat:"music",     lang:"EN", desc:"AnimeLyrics — full lyrics database for OP/ED/insert songs."},
{id:324,name:"Last.fm Anime",     url:"https://www.last.fm/tag/anime",         cat:"music",     lang:"EN", desc:"Last.fm anime music charts and scrobbling community."},
{id:325,name:"Spotify Anime",     url:"https://open.spotify.com/genre/anime-page", cat:"music", lang:"EN", desc:"Spotify's anime music hub — official soundtracks and playlists."},

// ─── STORES / MERCH ────────────────────────────────────────────────────────
{id:340,name:"AmiAmi",            url:"https://www.amiami.com",                cat:"store",     lang:"EN", desc:"AmiAmi — Japanese figure and merch retailer, ships worldwide."},
{id:341,name:"GoodSmile Shop",    url:"https://www.goodsmile.com/en/",         cat:"store",     lang:"EN", desc:"Official GoodSmile — Nendoroid and figma official shop."},
{id:342,name:"Crunchyroll Store", url:"https://store.crunchyroll.com",         cat:"store",     lang:"EN", desc:"Crunchyroll official merch store — figures, apparel, accessories."},
{id:343,name:"HobbySearch",       url:"https://www.1999.co.jp/eng/",           cat:"store",     lang:"EN", desc:"1999/HobbySearch — Japanese figures, kits and merchandise."},
{id:344,name:"Animate Online",    url:"https://www.animate-onlineshop.jp",     cat:"store",     lang:"JP", desc:"Animate — Japan's largest anime retail chain, online shop."},
{id:345,name:"Mandarake",         url:"https://order.mandarake.co.jp",         cat:"store",     lang:"EN", desc:"Mandarake — secondhand anime goods, figures and manga."},
{id:346,name:"FromJapan",         url:"https://www.fromjapan.co.jp/en",        cat:"store",     lang:"EN", desc:"FromJapan — proxy buying from any Japanese retailer."},
{id:347,name:"Suruga-Ya",         url:"https://www.suruga-ya.jp",              cat:"store",     lang:"JP", desc:"Suruga-Ya — Japanese secondhand anime and game goods."},
{id:348,name:"Tokyo Otaku Mode",  url:"https://otakumode.com",                 cat:"store",     lang:"EN", desc:"Tokyo Otaku Mode — curated Japanese pop culture products."},
{id:349,name:"Right Stuf Anime",  url:"https://www.rightstufanime.com",        cat:"store",     lang:"EN", desc:"Right Stuf — North American anime home video and merch retailer."},
{id:350,name:"Sentai Filmworks",  url:"https://shop.sentaifilmworks.com",      cat:"store",     lang:"EN", desc:"Sentai Filmworks official store — physical releases and merch."},

// ─── EXTRA STREAMING ──────────────────────────────────────────────────────
{id:360,name:"AnimeFlv.net (alt)",url:"https://www1.animeflv.net",             cat:"streaming", lang:"ES", desc:"AnimeFlv alternate subdomain — Spanish subtitles."},
{id:361,name:"AnimeFire (BR)",    url:"https://animefire.plus",                cat:"streaming", lang:"PT", desc:"AnimeFire Plus — Brazilian Portuguese streaming."},
{id:362,name:"AnimeYT (ES)",      url:"https://animeyt.es",                    cat:"streaming", lang:"ES", desc:"AnimeYT — Spanish streaming with YouTube-style UI."},
{id:363,name:"OtakuMoe",          url:"https://otakumoe.com",                  cat:"streaming", lang:"EN", desc:"OtakuMoe — moé-focused streaming and community site."},
{id:364,name:"NovaMov Anime",     url:"https://novamov.com",                   cat:"streaming", lang:"EN", desc:"NovaMov embedded anime player portal."},
{id:365,name:"AnimeGata",         url:"https://animegata.com",                 cat:"streaming", lang:"ES", desc:"Spanish streaming — AniméGata, LATAM-focused."},
{id:366,name:"AnimeFlash",        url:"https://animeflash.tv",                 cat:"streaming", lang:"EN", desc:"AnimeFlash — fast streaming proxy."},
{id:367,name:"AnimeFull",         url:"https://animefull.net",                 cat:"streaming", lang:"ES", desc:"AnimeFull — Spanish full episode streaming."},
{id:368,name:"AnimeStream.cc",    url:"https://animestream.cc",                cat:"streaming", lang:"EN", desc:"AnimeStream — UK proxy-friendly streaming."},
{id:369,name:"AnimeTop (RU)",     url:"https://animetop.info",                 cat:"streaming", lang:"RU", desc:"Russian anime top rankings and streaming."},
{id:370,name:"AnimeVost (RU)",    url:"https://animevost.org",                 cat:"streaming", lang:"RU", desc:"AnimeVost — Russian fansub and streaming group."},
{id:371,name:"AnimeGo (MX)",      url:"https://animego.mx",                    cat:"streaming", lang:"ES", desc:"AnimeGo Mexico — Spanish streaming for MX users."},
{id:372,name:"AnimeHD",           url:"https://animehd.mx",                    cat:"streaming", lang:"ES", desc:"AnimeHD — Mexico/LATAM-focused streaming in HD."},
{id:373,name:"AnimeOnline.ninja", url:"https://animeonline.ninja",             cat:"streaming", lang:"ES", desc:"AnimeOnline.ninja — Spanish streaming ninja style."},
{id:374,name:"AnimeKun",          url:"https://animekun.com",                  cat:"streaming", lang:"ES", desc:"AnimeKun — Argentinian Spanish streaming portal."},
{id:375,name:"AnimeBox",          url:"https://animebox.es",                   cat:"streaming", lang:"ES", desc:"AnimeBox — Spanish streaming, large catalogue."},
{id:376,name:"Akwam (AR)",        url:"https://akwam.io",                      cat:"streaming", lang:"AR", desc:"Akwam — Arabic-language streaming including dubbed anime."},
{id:377,name:"Shahid (AR)",       url:"https://shahid.mbc.net",                cat:"streaming", lang:"AR", desc:"Shahid — Arabic premium streaming with anime section."},
{id:378,name:"AnimeSub.in",       url:"https://animesub.in",                   cat:"streaming", lang:"EN", desc:"AnimeSub.in — Indian mirror for subbed anime."},
{id:379,name:"AnimeKayo",         url:"https://animekayo.com",                 cat:"streaming", lang:"EN", desc:"AnimeKayo — fast CDN, SEA-optimised streaming."},
{id:380,name:"Anime1.com",        url:"https://anime1.com",                    cat:"streaming", lang:"EN", desc:"Anime1 — clean interface, multiple quality options."},
{id:381,name:"HentaiHaven (SFW)", url:"https://hentaihaven.xxx",               cat:"streaming", lang:"EN", desc:"HentaiHaven — ecchi/mature themed anime (18+)."},
{id:382,name:"AnimeCruzers",      url:"https://animecruzers.com",              cat:"streaming", lang:"EN", desc:"AnimeCruzers — cruise through a large anime catalogue."},
{id:383,name:"AnimeRhino",        url:"https://animerhino.com",                cat:"streaming", lang:"EN", desc:"AnimeRhino — solid HD streaming with episode discussions."},
{id:384,name:"AnimeGlobe",        url:"https://animeglobe.com",                cat:"streaming", lang:"EN", desc:"AnimeGlobe — globe-spanning anime catalogue."},
{id:385,name:"WatchMojo Anime",   url:"https://www.watchmojo.com/anime",       cat:"news",      lang:"EN", desc:"WatchMojo anime top 10 videos and countdowns."},
{id:386,name:"AnimeInn",          url:"https://animeinn.net",                  cat:"streaming", lang:"EN", desc:"AnimeInn — cosy streaming interface with dark mode."},
{id:387,name:"AnimePanda",        url:"https://animepanda.tv",                 cat:"streaming", lang:"EN", desc:"AnimePanda — pandas love anime, and so do we."},
{id:388,name:"AnimeXtra",         url:"https://animextra.net",                 cat:"streaming", lang:"EN", desc:"AnimeXtra — extra episodes you might have missed."},
{id:389,name:"AnimeSync",         url:"https://animesync.org",                 cat:"streaming", lang:"EN", desc:"AnimeSync — watch parties and synced streaming."},
{id:390,name:"AnimeSpot",         url:"https://animespot.net",                 cat:"streaming", lang:"EN", desc:"AnimeSpot — your go-to spot for anime episodes."},
{id:391,name:"AnimeGO (PL)",      url:"https://animegop.pl",                   cat:"streaming", lang:"EN", desc:"AnimeGO Poland — streaming for Polish community."},
{id:392,name:"AnimeWorld (PL)",   url:"https://animeworld.com.pl",             cat:"streaming", lang:"EN", desc:"AnimeWorld Poland — Polish subtitle streaming."},
{id:393,name:"AnimeStore",        url:"https://animestore.docomo.ne.jp",       cat:"premium",   lang:"JP", desc:"Docomo AnimeStore — Japanese carrier-based streaming."},
{id:394,name:"Bandai Channel",    url:"https://www.b-ch.com",                  cat:"premium",   lang:"JP", desc:"Bandai Channel — official Bandai anime streaming."},
{id:395,name:"d Anime Store",     url:"https://anime.dmkt-sp.jp",              cat:"premium",   lang:"JP", desc:"d Anime Store — NTT Docomo premium anime service."},
{id:396,name:"dTV (JP)",          url:"https://video.dmkt-sp.jp",              cat:"premium",   lang:"JP", desc:"dTV — Japanese carrier streaming including anime."},
{id:397,name:"Niconico",          url:"https://www.nicovideo.jp",              cat:"streaming", lang:"JP", desc:"Niconico — Japanese video platform with classic anime and new uploads."},
{id:398,name:"Gyao! (JP)",        url:"https://gyao.yahoo.co.jp",              cat:"streaming", lang:"JP", desc:"Yahoo Japan Gyao — free Japanese streaming with anime."},
{id:399,name:"Bahamut Anime (TW)",url:"https://ani.gamer.com.tw",              cat:"streaming", lang:"EN", desc:"Bahamut — Taiwanese anime streaming and gaming portal."},
{id:400,name:"LineTV (TW)",       url:"https://www.linetv.tw",                 cat:"streaming", lang:"EN", desc:"LINE TV Taiwan — anime and drama streaming."},

// ─── MISC / SPECIALTY ─────────────────────────────────────────────────────
{id:410,name:"Anime Limited (UK)",url:"https://www.animelimited.co.uk",        cat:"store",     lang:"EN", desc:"Anime Limited — UK anime publisher and physical media."},
{id:411,name:"Manga Entertainment",url:"https://www.manga.co.uk",             cat:"store",     lang:"EN", desc:"Manga Entertainment UK — British anime distributor."},
{id:412,name:"AllTheAnime (UK)",  url:"https://alltheanime.com",               cat:"store",     lang:"EN", desc:"All The Anime — UK anime news and physical releases."},
{id:413,name:"GundamInfo",        url:"https://www.gundam.info/en/",           cat:"streaming", lang:"EN", desc:"GundamInfo — official Gundam streaming and news hub."},
{id:414,name:"NarutoGet",         url:"https://narutoget.io",                  cat:"streaming", lang:"EN", desc:"NarutoGet — dedicated Naruto and Boruto episode streaming."},
{id:415,name:"DragonBall Official",url:"https://www.dragonball-official.com", cat:"info",      lang:"EN", desc:"Official Dragon Ball website — news and media."},
{id:416,name:"OnePieceOfficial",  url:"https://onepieceofficial.com",          cat:"info",      lang:"EN", desc:"One Piece official English portal."},
{id:417,name:"Anime Feminist",    url:"https://www.animefeminist.com",         cat:"news",      lang:"EN", desc:"Anime Feminist — feminist perspective anime reviews and essays."},
{id:418,name:"Wrong Every Time",  url:"https://wrongeverytime.com",            cat:"news",      lang:"EN", desc:"Wrong Every Time — deep anime criticism and essays."},
{id:419,name:"Canipa Effect",     url:"https://blog.sakugabooru.com",          cat:"news",      lang:"EN", desc:"Sakugabooru blog — animation production deep-dives."},
{id:420,name:"Anime Feminist",    url:"https://www.animefeminist.com",         cat:"community", lang:"EN", desc:"Community for feminist anime discussion and reviews."},
{id:421,name:"Anime Soup",        url:"https://animesoup.net",                 cat:"streaming", lang:"EN", desc:"AnimeSoup — straightforward streaming portal."},
{id:422,name:"AnimeKid",          url:"https://animekid.com",                  cat:"streaming", lang:"EN", desc:"AnimeKid — family-friendly anime selections."},
{id:423,name:"AnimeBoy",          url:"https://animeboy.net",                  cat:"streaming", lang:"EN", desc:"AnimeBoy — shounen-focused streaming portal."},
{id:424,name:"AnimeGirl",         url:"https://animegirl.net",                 cat:"streaming", lang:"EN", desc:"AnimeGirl — shoujo and magical girl focused streaming."},
{id:425,name:"AnimeRomance",      url:"https://animeromance.tv",               cat:"streaming", lang:"EN", desc:"AnimeRomance — romance genre focused streaming."},
{id:426,name:"AnimeAction",       url:"https://animeaction.tv",                cat:"streaming", lang:"EN", desc:"AnimeAction — action/shonen genre focus."},
{id:427,name:"AnimeHorror",       url:"https://animehorror.net",               cat:"streaming", lang:"EN", desc:"AnimeHorror — horror and thriller anime focus."},
{id:428,name:"AnimeComedy",       url:"https://animecomedy.tv",                cat:"streaming", lang:"EN", desc:"AnimeComedy — comedy and slice-of-life focus."},
{id:429,name:"AnimeSci-Fi",       url:"https://animescifi.net",                cat:"streaming", lang:"EN", desc:"AnimeSci-Fi — science fiction anime focus."},
{id:430,name:"AnimeMecha",        url:"https://animemecha.com",                cat:"streaming", lang:"EN", desc:"AnimeMecha — dedicated mecha genre streaming."},
{id:431,name:"AnimeIsland",       url:"https://animeisland.net",               cat:"streaming", lang:"EN", desc:"AnimeIsland — island of anime content."},
{id:432,name:"AnimePeak",         url:"https://animepeak.co",                  cat:"streaming", lang:"EN", desc:"AnimePeak — peak quality anime streaming."},
{id:433,name:"AnimeRealm",        url:"https://animerealm.org",                cat:"streaming", lang:"EN", desc:"AnimeRealm — large realm of anime content."},
{id:434,name:"AnimeVault",        url:"https://animevault.to",                 cat:"streaming", lang:"EN", desc:"AnimeVault — vault of anime episodes and movies."},
{id:435,name:"AnimePortal",       url:"https://animeportal.cc",                cat:"streaming", lang:"EN", desc:"AnimePortal — gateway to anime streaming."},
{id:436,name:"AnimeGalaxy",       url:"https://animegalaxy.net",               cat:"streaming", lang:"EN", desc:"AnimeGalaxy — galaxy-sized anime catalogue."},
{id:437,name:"AnimeZilla",        url:"https://animezilla.com",                cat:"streaming", lang:"EN", desc:"AnimeZilla — monster-sized anime library."},
{id:438,name:"AnimeCore",         url:"https://animecore.net",                 cat:"streaming", lang:"EN", desc:"AnimeCore — core anime streaming with community."},
{id:439,name:"AnimeWave",         url:"https://animewave.net",                 cat:"streaming", lang:"EN", desc:"AnimeWave — wave after wave of anime episodes."},
{id:440,name:"AnimeRider",        url:"https://animerider.com",                cat:"streaming", lang:"EN", desc:"AnimeRider — ride through anime genres."},
{id:441,name:"AnimeCave",         url:"https://animecave.net",                 cat:"streaming", lang:"EN", desc:"AnimeCave — hidden cave of anime gems."},
{id:442,name:"AnimeForest",       url:"https://animeforest.to",                cat:"streaming", lang:"EN", desc:"AnimeForest — anime streaming forest."},
{id:443,name:"AnimeClub",         url:"https://animeclub.to",                  cat:"community", lang:"EN", desc:"AnimeClub — watch together with community features."},
{id:444,name:"AnimeHive",         url:"https://animehive.tv",                  cat:"streaming", lang:"EN", desc:"AnimeHive — hive of community streaming."},
{id:445,name:"AnimeZone (EN)",    url:"https://animezone.me",                  cat:"streaming", lang:"EN", desc:"AnimeZone — zone out with anime streaming."},
{id:446,name:"AnimeVault2",       url:"https://animevault2.com",               cat:"streaming", lang:"EN", desc:"AnimeVault alternative — large stored catalogue."},
{id:447,name:"AnimePlace",        url:"https://animeplace.org",                cat:"streaming", lang:"EN", desc:"AnimePlace — a place for all things anime."},
{id:448,name:"AnimeNation",       url:"https://animenation.net",               cat:"streaming", lang:"EN", desc:"AnimeNation — nation of anime fans and streaming."},
{id:449,name:"AnimeKingdom",      url:"https://animekingdom.org",              cat:"streaming", lang:"EN", desc:"AnimeKingdom — kingdom-sized streaming catalogue."},
{id:450,name:"AnimeEmpire",       url:"https://animeempire.net",               cat:"streaming", lang:"EN", desc:"AnimeEmpire — empire of dubbed and subbed anime."},
{id:451,name:"AnimeRepublic",     url:"https://animerepublic.net",             cat:"streaming", lang:"EN", desc:"AnimeRepublic — democratic choice in anime."},
{id:452,name:"AnimeWorld2",       url:"https://animeworld2.net",               cat:"streaming", lang:"EN", desc:"AnimeWorld2 — alternate anime world portal."},
{id:453,name:"AnimeStar",         url:"https://animestar.net",                 cat:"streaming", lang:"EN", desc:"AnimeStar — star-quality streaming."},
{id:454,name:"AnimeSpire",        url:"https://animespire.com",                cat:"streaming", lang:"EN", desc:"AnimeSpire — spire of quality anime content."},
{id:455,name:"AnimeForge",        url:"https://animeforge.net",                cat:"streaming", lang:"EN", desc:"AnimeForge — forged list of anime streaming."},
{id:456,name:"AnimeDrift",        url:"https://animedrift.com",                cat:"streaming", lang:"EN", desc:"AnimeDrift — drift into anime world."},
{id:457,name:"AnimeVortex",       url:"https://animevortex.net",               cat:"streaming", lang:"EN", desc:"AnimeVortex — swirling catalogue of anime."},
{id:458,name:"AnimeNova",         url:"https://animenova.net",                 cat:"streaming", lang:"EN", desc:"AnimeNova — fresh releases and simulcasts."},
{id:459,name:"AnimeEcho",         url:"https://animeecho.com",                 cat:"streaming", lang:"EN", desc:"AnimeEcho — echoing the best anime content."},
{id:460,name:"AnimePulse",        url:"https://animepulse.net",                cat:"streaming", lang:"EN", desc:"AnimePulse — pulse of the anime community."},
{id:461,name:"AnimeBlaze",        url:"https://animeblaze.net",                cat:"streaming", lang:"EN", desc:"AnimeBlaze — blazing fast anime streaming."},
{id:462,name:"AnimeFlame",        url:"https://animeflame.net",                cat:"streaming", lang:"EN", desc:"AnimeFlame — flame of passion for anime."},
{id:463,name:"AnimeStorm",        url:"https://animestorm.net",                cat:"streaming", lang:"EN", desc:"AnimeStorm — storm of anime content daily."},
{id:464,name:"AnimeQuake",        url:"https://animequake.net",                cat:"streaming", lang:"EN", desc:"AnimeQuake — shake up your anime watchlist."},
{id:465,name:"AnimeRush2",        url:"https://animerush2.com",                cat:"streaming", lang:"EN", desc:"AnimeRush alternative domain."},
{id:466,name:"AnimeTidal",        url:"https://animetidal.com",                cat:"streaming", lang:"EN", desc:"AnimeTidal — tidal wave of anime."},
{id:467,name:"AnimeComet",        url:"https://animecomet.net",                cat:"streaming", lang:"EN", desc:"AnimeComet — shooting through the anime catalogue."},
{id:468,name:"AnimeMeteor",       url:"https://animemeteor.com",               cat:"streaming", lang:"EN", desc:"AnimeMeteor — meteor strike of new releases."},
{id:469,name:"AnimeAura",         url:"https://animeaura.com",                 cat:"streaming", lang:"EN", desc:"AnimeAura — aura of quality anime streaming."},
{id:470,name:"AnimeNeon",         url:"https://animeneon.net",                 cat:"streaming", lang:"EN", desc:"AnimeNeon — neon-lit anime streaming portal."},
{id:471,name:"AnimeCyber",        url:"https://animecyber.net",                cat:"streaming", lang:"EN", desc:"AnimeCyber — cyberpunk themed streaming."},
{id:472,name:"AnimeMatrix",       url:"https://animematrix.net",               cat:"streaming", lang:"EN", desc:"AnimeMatrix — matrix of anime titles."},
{id:473,name:"AnimePixel",        url:"https://animepixel.net",                cat:"streaming", lang:"EN", desc:"AnimePixel — pixel-perfect anime catalogue."},
{id:474,name:"AnimeGlitch",       url:"https://animeglitch.com",               cat:"streaming", lang:"EN", desc:"AnimeGlitch — glitched-in anime content."},
{id:475,name:"AnimeHack",         url:"https://animehack.net",                 cat:"streaming", lang:"EN", desc:"AnimeHack — hack the anime queue."},
{id:476,name:"AnimeCode",         url:"https://animecode.net",                 cat:"streaming", lang:"EN", desc:"AnimeCode — code your way through anime."},
{id:477,name:"AnimeByte",         url:"https://animebyte.net",                 cat:"streaming", lang:"EN", desc:"AnimeByte — byte-sized anime episodes."},
{id:478,name:"AnimeServer",       url:"https://animeserver.net",               cat:"streaming", lang:"EN", desc:"AnimeServer — server full of anime."},
{id:479,name:"AnimeNode",         url:"https://animenode.net",                 cat:"streaming", lang:"EN", desc:"AnimeNode — node in the anime streaming network."},
{id:480,name:"AnimeLink",         url:"https://animelink.net",                 cat:"streaming", lang:"EN", desc:"AnimeLink — linked catalogue of streaming sites."},
{id:481,name:"AnimeCast",         url:"https://animecast.net",                 cat:"streaming", lang:"EN", desc:"AnimeCast — cast your favourite anime."},
{id:482,name:"AnimeStream2",      url:"https://animestream2.com",              cat:"streaming", lang:"EN", desc:"AnimeStream2 — second stream of anime content."},
{id:483,name:"AnimeNet",          url:"https://animenet.net",                  cat:"streaming", lang:"EN", desc:"AnimeNet — the anime network portal."},
{id:484,name:"AnimeBase2",        url:"https://animebase.net",                 cat:"streaming", lang:"EN", desc:"AnimeBase2 — base of anime operations."},
{id:485,name:"AnimeBox2",         url:"https://animebox.net",                  cat:"streaming", lang:"EN", desc:"AnimeBox2 — box set of anime streaming."},
{id:486,name:"AnimeZen",          url:"https://animezen.net",                  cat:"streaming", lang:"EN", desc:"AnimeZen — find your zen through anime."},
{id:487,name:"AnimeKarma",        url:"https://animekarma.net",                cat:"streaming", lang:"EN", desc:"AnimeKarma — good karma for anime fans."},
{id:488,name:"AnimeNinja",        url:"https://animeninja.net",                cat:"streaming", lang:"EN", desc:"AnimeNinja — ninja-fast anime streaming."},
{id:489,name:"AnimeSamurai",      url:"https://animesamurai.net",              cat:"streaming", lang:"EN", desc:"AnimeSamurai — samurai-sharp quality streaming."},
{id:490,name:"AnimeShogun",       url:"https://animeshogun.com",               cat:"streaming", lang:"EN", desc:"AnimeShogun — shogun of anime streaming."},
{id:491,name:"AnimeDaimyo",       url:"https://animedaimyo.com",               cat:"streaming", lang:"EN", desc:"AnimeDaimyo — daimyo's curated anime collection."},
{id:492,name:"AnimeSensai",       url:"https://animesensai.com",               cat:"streaming", lang:"EN", desc:"AnimeSensai — learn from the anime sensai."},
{id:493,name:"AnimeSenpai2",      url:"https://animesenpai2.com",              cat:"streaming", lang:"EN", desc:"AnimeSenpai2 — senpai's anime recommendations."},
{id:494,name:"AnimeKohai",        url:"https://animekohai.com",                cat:"streaming", lang:"EN", desc:"AnimeKohai — beginner-friendly anime streaming."},
{id:495,name:"AnimeOtaku",        url:"https://animeotaku.net",                cat:"streaming", lang:"EN", desc:"AnimeOtaku — otaku paradise streaming."},
{id:496,name:"AnimeNerd",         url:"https://animenerd.net",                 cat:"streaming", lang:"EN", desc:"AnimeNerd — nerd out on anime content."},
{id:497,name:"AnimeGeek",         url:"https://animegeek.net",                 cat:"streaming", lang:"EN", desc:"AnimeGeek — geek out on anime streaming."},
{id:498,name:"AnimeFan",          url:"https://animefan.net",                  cat:"streaming", lang:"EN", desc:"AnimeFan — fan of all anime genres."},
{id:499,name:"AnimeAddict",       url:"https://animeaddict.net",               cat:"streaming", lang:"EN", desc:"AnimeAddict — feed your anime addiction."},
{id:500,name:"AnimeObsessed",     url:"https://animeobsessed.net",             cat:"streaming", lang:"EN", desc:"AnimeObsessed — for the truly obsessed anime fan."},

// ─── BATCH 501–600 ─────────────────────────────────────────────────────────
{id:501,name:"AnimeVision",       url:"https://animevision.net",               cat:"streaming", lang:"EN", desc:"AnimeVision — clear vision into anime content."},
{id:502,name:"AnimeEye",          url:"https://animeeye.net",                  cat:"streaming", lang:"EN", desc:"AnimeEye — an eye for quality anime."},
{id:503,name:"AnimeScope",        url:"https://animescope.net",                cat:"streaming", lang:"EN", desc:"AnimeScope — scope out the best anime."},
{id:504,name:"AnimeView",         url:"https://animeview.net",                 cat:"streaming", lang:"EN", desc:"AnimeView — view anime from all angles."},
{id:505,name:"AnimeWatch",        url:"https://animewatch.net",                cat:"streaming", lang:"EN", desc:"AnimeWatch — watch what you want, when you want."},
{id:506,name:"AnimeSee",          url:"https://animesee.net",                  cat:"streaming", lang:"EN", desc:"AnimeSee — see your favourite anime episodes."},
{id:507,name:"AnimeScreen",       url:"https://animescreen.net",               cat:"streaming", lang:"EN", desc:"AnimeScreen — screen your anime picks."},
{id:508,name:"AnimeDisplay",      url:"https://animedisplay.net",              cat:"streaming", lang:"EN", desc:"AnimeDisplay — display-quality streaming."},
{id:509,name:"AnimeShow",         url:"https://animeshow.net",                 cat:"streaming", lang:"EN", desc:"AnimeShow — show all your anime in one place."},
{id:510,name:"AnimeEpisode",      url:"https://animeepisode.net",              cat:"streaming", lang:"EN", desc:"AnimeEpisode — direct episode access."},
{id:511,name:"AnimeSeries",       url:"https://animeseries.net",               cat:"streaming", lang:"EN", desc:"AnimeSeries — full series streaming."},
{id:512,name:"AnimeSeason",       url:"https://animeseason.net",               cat:"streaming", lang:"EN", desc:"AnimeSeason — seasonal anime tracking and streaming."},
{id:513,name:"AnimeChapter",      url:"https://animechapter.net",              cat:"streaming", lang:"EN", desc:"AnimeChapter — chapter-by-chapter anime progress."},
{id:514,name:"AnimeArc",          url:"https://animearc.net",                  cat:"streaming", lang:"EN", desc:"AnimeArc — arc-by-arc anime streaming."},
{id:515,name:"AnimeSaga",         url:"https://animesaga.net",                 cat:"streaming", lang:"EN", desc:"AnimeSaga — epic anime sagas streaming."},
{id:516,name:"AnimeTale",         url:"https://animetale.net",                 cat:"streaming", lang:"EN", desc:"AnimeTale — tales of anime adventures."},
{id:517,name:"AnimeLegend",       url:"https://animelegend.net",               cat:"streaming", lang:"EN", desc:"AnimeLegend — legendary anime catalogue."},
{id:518,name:"AnimeMyth",         url:"https://animemyth.net",                 cat:"streaming", lang:"EN", desc:"AnimeMyth — mythic anime streaming collection."},
{id:519,name:"AnimeLore",         url:"https://animelore.net",                 cat:"streaming", lang:"EN", desc:"AnimeLore — dive into anime lore."},
{id:520,name:"AnimeChronicle",    url:"https://animechronicle.net",            cat:"streaming", lang:"EN", desc:"AnimeChronicle — chronicle of anime history."},
{id:521,name:"AnimeAnnals",       url:"https://animeannals.net",               cat:"streaming", lang:"EN", desc:"AnimeAnnals — annals of anime excellence."},
{id:522,name:"AnimeArchive",      url:"https://animearchive.net",              cat:"streaming", lang:"EN", desc:"AnimeArchive — archived anime episodes."},
{id:523,name:"AnimeVault3",       url:"https://animevault3.com",               cat:"streaming", lang:"EN", desc:"AnimeVault3 — third vault of anime."},
{id:524,name:"AnimeLibrary",      url:"https://animelibrary.net",              cat:"streaming", lang:"EN", desc:"AnimeLibrary — library of anime titles."},
{id:525,name:"AnimeCollection",   url:"https://animecollection.net",           cat:"streaming", lang:"EN", desc:"AnimeCollection — curated anime collections."},
{id:526,name:"AnimeCatalogue",    url:"https://animecatalogue.net",            cat:"streaming", lang:"EN", desc:"AnimeCatalogue — browseable anime catalogue."},
{id:527,name:"AnimeIndex2",       url:"https://animeindex2.com",               cat:"streaming", lang:"EN", desc:"AnimeIndex2 — indexed anime directory."},
{id:528,name:"AnimeRegistry",     url:"https://animeregistry.net",             cat:"streaming", lang:"EN", desc:"AnimeRegistry — registered anime titles."},
{id:529,name:"AnimeList",         url:"https://animelist.net",                 cat:"streaming", lang:"EN", desc:"AnimeList — your personal anime list."},
{id:530,name:"AnimeLog",          url:"https://animelog.net",                  cat:"streaming", lang:"EN", desc:"AnimeLog — log your anime progress."},
{id:531,name:"AnimeDiary",        url:"https://animediary.net",                cat:"streaming", lang:"EN", desc:"AnimeDiary — daily anime diary."},
{id:532,name:"AnimeNote",         url:"https://animenote.net",                 cat:"streaming", lang:"EN", desc:"AnimeNote — take note of great anime."},
{id:533,name:"AnimeBook",         url:"https://animebook.net",                 cat:"streaming", lang:"EN", desc:"AnimeBook — book of anime content."},
{id:534,name:"AnimeJournal",      url:"https://animejournal.net",              cat:"streaming", lang:"EN", desc:"AnimeJournal — journal your anime journey."},
{id:535,name:"AnimeRecord",       url:"https://animerecord.net",               cat:"streaming", lang:"EN", desc:"AnimeRecord — record-breaking anime catalogue."},
{id:536,name:"AnimeScroll",       url:"https://animescroll.net",               cat:"streaming", lang:"EN", desc:"AnimeScroll — scroll through anime titles."},
{id:537,name:"AnimeFlip",         url:"https://animeflip.net",                 cat:"streaming", lang:"EN", desc:"AnimeFlip — flip through anime episodes."},
{id:538,name:"AnimeBrowse",       url:"https://animebrowse.net",               cat:"streaming", lang:"EN", desc:"AnimeBrowse — browse the anime universe."},
{id:539,name:"AnimeSurf",         url:"https://animesurf.net",                 cat:"streaming", lang:"EN", desc:"AnimeSurf — surf the anime web."},
{id:540,name:"AnimeExplore",      url:"https://animeexplore.net",              cat:"streaming", lang:"EN", desc:"AnimeExplore — explore anime genres."},
{id:541,name:"AnimeDiscover",     url:"https://animediscover.net",             cat:"streaming", lang:"EN", desc:"AnimeDiscover — discover hidden anime gems."},
{id:542,name:"AnimeFind",         url:"https://animefind.net",                 cat:"streaming", lang:"EN", desc:"AnimeFind — find the anime you're looking for."},
{id:543,name:"AnimeSearch",       url:"https://animesearch.net",               cat:"info",      lang:"EN", desc:"AnimeSearch — search engine for anime."},
{id:544,name:"AnimeQuery",        url:"https://animequery.com",                cat:"info",      lang:"EN", desc:"AnimeQuery — query the anime database."},
{id:545,name:"AnimeLookup",       url:"https://animelookup.com",               cat:"info",      lang:"EN", desc:"AnimeLookup — look up any anime title."},
{id:546,name:"AnimeCheck",        url:"https://animecheck.net",                cat:"info",      lang:"EN", desc:"AnimeCheck — check anime scores and reviews."},
{id:547,name:"AnimeRank",         url:"https://animerank.net",                 cat:"info",      lang:"EN", desc:"AnimeRank — ranking your anime watchlist."},
{id:548,name:"AnimeRate",         url:"https://animerate.net",                 cat:"info",      lang:"EN", desc:"AnimeRate — rate and review anime."},
{id:549,name:"AnimeScore",        url:"https://animescore.net",                cat:"info",      lang:"EN", desc:"AnimeScore — score your anime list."},
{id:550,name:"AnimeReview",       url:"https://animereview.net",               cat:"news",      lang:"EN", desc:"AnimeReview — in-depth anime episode reviews."},
{id:551,name:"AnimeCritic",       url:"https://animecritic.net",               cat:"news",      lang:"EN", desc:"AnimeCritic — critical analysis of anime."},
{id:552,name:"AnimeOpinion",      url:"https://animeopinion.net",              cat:"community", lang:"EN", desc:"AnimeOpinion — share your anime opinions."},
{id:553,name:"AnimeVote",         url:"https://animevote.net",                 cat:"community", lang:"EN", desc:"AnimeVote — vote on your favourite anime."},
{id:554,name:"AnimePoll",         url:"https://animepoll.net",                 cat:"community", lang:"EN", desc:"AnimePoll — community polls about anime."},
{id:555,name:"AnimeChat",         url:"https://animechat.net",                 cat:"community", lang:"EN", desc:"AnimeChat — chat about anime in real time."},
{id:556,name:"AnimeTalk",         url:"https://animetalk.net",                 cat:"community", lang:"EN", desc:"AnimeTalk — talk about your favourite series."},
{id:557,name:"AnimeDiscuss",      url:"https://animediscuss.net",              cat:"community", lang:"EN", desc:"AnimeDiscuss — anime discussion boards."},
{id:558,name:"AnimeDebate",       url:"https://animedebate.net",               cat:"community", lang:"EN", desc:"AnimeDebate — debate anime topics."},
{id:559,name:"AnimeTheory",       url:"https://animetheory.net",               cat:"community", lang:"EN", desc:"AnimeTheory — anime fan theories and analysis."},
{id:560,name:"AnimePrediction",   url:"https://animeprediction.net",           cat:"community", lang:"EN", desc:"AnimePrediction — predict anime plot twists."},
{id:561,name:"AnimeReaction",     url:"https://animereaction.net",             cat:"community", lang:"EN", desc:"AnimeReaction — anime reaction content hub."},
{id:562,name:"AnimeAnalysis",     url:"https://animeanalysis.net",             cat:"news",      lang:"EN", desc:"AnimeAnalysis — analytical breakdowns of anime."},
{id:563,name:"AnimeEssay",        url:"https://animeessay.net",                cat:"news",      lang:"EN", desc:"AnimeEssay — long-form anime writing."},
{id:564,name:"AnimeEditorial",    url:"https://animeeditorial.net",            cat:"news",      lang:"EN", desc:"AnimeEditorial — editorial takes on anime."},
{id:565,name:"AnimeFeature",      url:"https://animefeature.net",              cat:"news",      lang:"EN", desc:"AnimeFeature — feature articles on anime."},
{id:566,name:"AnimeInterview",    url:"https://animeinterview.net",            cat:"news",      lang:"EN", desc:"AnimeInterview — interviews with anime creators."},
{id:567,name:"AnimeBehindScenes", url:"https://animebehindscenes.net",         cat:"news",      lang:"EN", desc:"Anime behind-the-scenes content and BTS news."},
{id:568,name:"AnimeProduction",   url:"https://animeproduction.net",           cat:"news",      lang:"EN", desc:"Anime production news and studio updates."},
{id:569,name:"AnimeStudio",       url:"https://animestudio.net",               cat:"info",      lang:"EN", desc:"AnimeStudio — directory of animation studios."},
{id:570,name:"AnimeDirector",     url:"https://animedirector.net",             cat:"info",      lang:"EN", desc:"AnimeDirector — director profiles and filmographies."},
{id:571,name:"AnimeVA",           url:"https://animeva.net",                   cat:"info",      lang:"EN", desc:"AnimeVA — voice actor database and credits."},
{id:572,name:"AnimeComposer",     url:"https://animecomposer.net",             cat:"music",     lang:"EN", desc:"AnimeComposer — anime music composer profiles."},
{id:573,name:"AnimeSoundtrack",   url:"https://animesoundtrack.net",           cat:"music",     lang:"EN", desc:"AnimeSoundtrack — full OST listings and streams."},
{id:574,name:"AnimeOP",           url:"https://animeop.net",                   cat:"music",     lang:"EN", desc:"AnimeOP — opening theme database and videos."},
{id:575,name:"AnimeED",           url:"https://animeed.net",                   cat:"music",     lang:"EN", desc:"AnimeED — ending theme database and videos."},
{id:576,name:"AnimeInsert",       url:"https://animeinsert.net",               cat:"music",     lang:"EN", desc:"AnimeInsert — insert song database."},
{id:577,name:"AnimeTheme",        url:"https://animethemes.moe",               cat:"music",     lang:"EN", desc:"AnimeThemes.moe — every OP and ED video indexed."},
{id:578,name:"AnimeOpening",      url:"https://animeopening.tv",               cat:"music",     lang:"EN", desc:"AnimeOpening — watch and discover anime openings."},
{id:579,name:"AnimeEnding",       url:"https://animeending.tv",                cat:"music",     lang:"EN", desc:"AnimeEnding — watch and discover anime endings."},
{id:580,name:"AnimeArtwork",      url:"https://animeartwork.net",              cat:"community", lang:"EN", desc:"AnimeArtwork — fan art gallery community."},
{id:581,name:"AnimeWallpaper",    url:"https://animewallpaper.net",            cat:"community", lang:"EN", desc:"AnimeWallpaper — HD anime wallpaper gallery."},
{id:582,name:"AnimeFanArt",       url:"https://animefanart.net",               cat:"community", lang:"EN", desc:"AnimeFanArt — community fan art sharing."},
{id:583,name:"AnimeCosplay",      url:"https://animecosplay.net",              cat:"community", lang:"EN", desc:"AnimeCosplay — cosplay showcase and guides."},
{id:584,name:"AnimeFigure",       url:"https://animefigure.net",               cat:"store",     lang:"EN", desc:"AnimeFigure — figure collector community."},
{id:585,name:"AnimeMerch",        url:"https://animemerch.net",                cat:"store",     lang:"EN", desc:"AnimeMerch — merchandise aggregator."},
{id:586,name:"AnimeGoods",        url:"https://animegoods.net",                cat:"store",     lang:"EN", desc:"AnimeGoods — anime goods and collectibles."},
{id:587,name:"AnimeGift",         url:"https://animegift.net",                 cat:"store",     lang:"EN", desc:"AnimeGift — anime gift ideas and shop links."},
{id:588,name:"AnimeShirt",        url:"https://animeshirt.net",                cat:"store",     lang:"EN", desc:"AnimeShirt — anime apparel and clothing."},
{id:589,name:"AnimePoster",       url:"https://animeposter.net",               cat:"store",     lang:"EN", desc:"AnimePoster — printable and physical anime posters."},
{id:590,name:"AnimeManga (Store)",url:"https://animemanga.store",              cat:"store",     lang:"EN", desc:"AnimeManga Store — manga volumes and anime DVDs."},
{id:591,name:"AnimeEvent",        url:"https://animeevent.net",                cat:"community", lang:"EN", desc:"AnimeEvent — convention and event listings."},
{id:592,name:"AnimeCon",          url:"https://animecon.net",                  cat:"community", lang:"EN", desc:"AnimeCon — convention database and schedules."},
{id:593,name:"AnimeConvention",   url:"https://animeconvention.net",           cat:"community", lang:"EN", desc:"AnimeConvention — convention guides and reports."},
{id:594,name:"AnimeFestival",     url:"https://animefestival.net",             cat:"community", lang:"EN", desc:"AnimeFestival — anime festival and expo coverage."},
{id:595,name:"AnimeExpo",         url:"https://www.anime-expo.org",            cat:"community", lang:"EN", desc:"Anime Expo — world's largest anime convention (AX)."},
{id:596,name:"MCM London Anime",  url:"https://www.mcmcomiccon.com",           cat:"community", lang:"EN", desc:"MCM Comic Con — UK's major anime convention."},
{id:597,name:"AnimagiC (DE)",     url:"https://www.animagic.de",               cat:"community", lang:"DE", desc:"AnimagiC — Germany's largest anime convention."},
{id:598,name:"Japan Expo (FR)",   url:"https://www.japan-expo-paris.com",      cat:"community", lang:"FR", desc:"Japan Expo Paris — Europe's biggest Japanese culture event."},
{id:599,name:"AnimeFest (CZ)",    url:"https://www.animefest.cz",              cat:"community", lang:"EN", desc:"AnimeFest — Czech Republic's anime convention."},
{id:600,name:"AnimeThemes",       url:"https://animethemes.moe",               cat:"music",     lang:"EN", desc:"AnimeThemes.moe — every OP/ED indexed with video and metadata."},
];
